spring.datasource.url=jdbc:postgresql://localhost:5432/Finances
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:my-secret-key}